# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Python Crash Course
subtitle: Introduction to Python for Biomedical Innovation
author: University of Edinburgh, School of Informatics
logo: logo.png
copyright: "2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  exclude_output: true 

remove:
  remove_output_tags:
    - hide-output
  remove_input_tags:
    - hide-input


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    - linkify
    - colon_fence
    - dollarmath
    - amsmath
    - deflist
    - html_admonition
    - html_image
    - smartquotes
    - substitution


# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  extra_extensions:
    - sphinx_thebe
    - myst_nb
  config:
    bibtex_reference_style: author_year
    pygments_style: monokai
    theme_options:
      default_mode: dark
  extra:
    copyright: "2025"

# Information about where the book exists on the web
repository:
  url: https://github.com/hanane-issa/python-crash-course  
  branch: hanane 

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_css:
    - _static/custom.css
  static_path: ['_static']


launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  thebe                  : true
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  colab_url: "https://colab.research.google.com"


