name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main   # change if your source branch is different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # pick the Python you use locally

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book ghp-import
          # optionally install project dependencies:
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build Jupyter Book
        run: |
          jupyter-book build .

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f _build/html
